# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='gardenbotvr/models')),
                ('thumb', models.ImageField(upload_to='gardenbotvr/thumbs')),
                ('is_moving', models.BooleanField(default=False)),
                ('dchord', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='gardenbotvr/models')),
                ('thumb', models.ImageField(upload_to='gardenbotvr/thumbs')),
                ('uploaded', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('thumb', models.ImageField(upload_to='gardenbotvr/scenes')),
                ('template', models.CharField(max_length=30)),
                ('skycolor', models.CharField(default='#aaffe8', max_length=30)),
                ('groundcolor', models.CharField(default='#c0ff82', max_length=30)),
                ('assets', models.ManyToManyField(to='gardenbotvr.Asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='bchord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_assets', to='gardenbotvr.Coordinate'),
        ),
        migrations.AddField(
            model_name='asset',
            name='fchord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_assets', to='gardenbotvr.Coordinate'),
        ),
    ]
