# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenbotvr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='model_shader',
            field=models.CharField(default='flat', max_length=30),
        ),
        migrations.AddField(
            model_name='entity',
            name='model_shader',
            field=models.CharField(default='flat', max_length=30),
        ),
        migrations.AddField(
            model_name='scene',
            name='ground_material',
            field=models.CharField(default='flat', max_length=30),
        ),
    ]
