# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenbotvr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='slug',
            field=models.SlugField(default='garden', editable=False),
            preserve_default=False,
        ),
    ]
