# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenbotvr', '0002_auto_20170905_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threed',
            name='type',
            field=models.CharField(choices=[('ENT', 'ENTITY'), ('SCN', 'SCENE')], max_length=30),
        ),
    ]
