# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenbotvr', '0002_auto_20170920_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='model_shader',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='model_shader',
        ),
    ]
