# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardenbotvr', '0003_auto_20170914_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='gardenbotvr/models')),
                ('thumb', models.ImageField(upload_to='gardenbotvr/thumbs')),
                ('uploaded', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('template', models.CharField(max_length=30)),
                ('skycolor', models.CharField(default='#aaffe8', max_length=30)),
                ('groundcolor', models.CharField(default='#c0ff82', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='ThreeD',
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gardenbotvr.Entity')),
                ('is_moving', models.BooleanField(default=False)),
                ('dchord', models.IntegerField(blank=True, null=True)),
                ('bchord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_assets', to='gardenbotvr.Coordinate')),
                ('fchord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_assets', to='gardenbotvr.Coordinate')),
            ],
            bases=('gardenbotvr.entity',),
        ),
        migrations.AddField(
            model_name='scene',
            name='assets',
            field=models.ManyToManyField(to='gardenbotvr.Asset'),
        ),
    ]
