# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardenbotvr', '0004_auto_20170922_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('coordinate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gardenbotvr.Coordinate')),
            ],
            bases=('gardenbotvr.coordinate',),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='rotation',
            field=models.ManyToManyField(to='gardenbotvr.Rotation'),
        ),
    ]
