# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardenbotvr', '0005_auto_20170922_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='rotation',
        ),
        migrations.AddField(
            model_name='asset',
            name='rotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gardenbotvr.Rotation'),
            preserve_default=False,
        ),
    ]
